# Generated by Django 5.2.16 on 2026-07-25 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('project_code', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('IN_PROGRESS', 'In Progress'), ('ON_HOLD', 'On Hold'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PLANNED', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employees', models.ManyToManyField(blank=True, related_name='projects', to='employees.employee')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='projects_pr_name_11d782_idx'), models.Index(fields=['project_code'], name='projects_pr_project_0def5e_idx'), models.Index(fields=['status'], name='projects_pr_status_f023cb_idx')],
            },
        ),
    ]
